// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheOffice.Persistence;

#nullable disable

namespace TheOffice.Persistence.Migrations
{
    [DbContext(typeof(TheOfficeDbContext))]
    [Migration("20260829221349_MarcadoresDeImagenEnTonosCalidos")]
    partial class MarcadoresDeImagenEnTonosCalidos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("TheOffice.Persistence.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c0000000-0000-4000-8000-000000000001"),
                            Description = "Papel, cuadernos y utiles de escritura para el dia a dia de la oficina.",
                            Name = "Papeleria",
                            PublicId = "CAT-001",
                            Slug = "papeleria"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-4000-8000-000000000002"),
                            Description = "Sillas, escritorios y archivadores para espacios de trabajo.",
                            Name = "Mobiliario",
                            PublicId = "CAT-002",
                            Slug = "mobiliario"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-4000-8000-000000000003"),
                            Description = "Monitores, perifericos y accesorios para puestos de trabajo digitales.",
                            Name = "Tecnologia",
                            PublicId = "CAT-003",
                            Slug = "tecnologia"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-4000-8000-000000000004"),
                            Description = "Archivo, clasificacion y orden del puesto de trabajo.",
                            Name = "Organizacion",
                            PublicId = "CAT-004",
                            Slug = "organizacion"
                        });
                });

            modelBuilder.Entity("TheOffice.Persistence.Models.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0000000-0000-4000-8000-000000000001"),
                            Email = "laura.restrepo@example.com",
                            Name = "Laura Restrepo",
                            PublicId = "CUS-001",
                            Source = 0
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-4000-8000-000000000002"),
                            Email = "andres.gomez@example.com",
                            Name = "Andres Gomez",
                            PublicId = "CUS-002",
                            Source = 3
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-4000-8000-000000000003"),
                            Email = "marcela.rios@example.com",
                            Name = "Marcela Rios",
                            PublicId = "CUS-003",
                            Source = 1
                        });
                });

            modelBuilder.Entity("TheOffice.Persistence.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b0000000-0000-4000-8000-000000000001"),
                            CategoryId = new Guid("c0000000-0000-4000-8000-000000000001"),
                            Description = "Resma de 500 hojas tamano carta, 75 gramos, blancura 96%.",
                            IsActive = true,
                            Name = "Resma de papel carta 75g",
                            Price = 18900.0,
                            PublicId = "PRD-001",
                            Stock = 120
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-4000-8000-000000000002"),
                            CategoryId = new Guid("c0000000-0000-4000-8000-000000000001"),
                            Description = "Cuaderno argollado tamano carta, 100 hojas cuadriculadas, pasta dura.",
                            IsActive = true,
                            Name = "Cuaderno argollado 100 hojas",
                            Price = 12500.0,
                            PublicId = "PRD-002",
                            Stock = 200
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-4000-8000-000000000003"),
                            CategoryId = new Guid("c0000000-0000-4000-8000-000000000001"),
                            Description = "Caja por 12 boligrafos de tinta negra, punta media de 1.0 mm.",
                            IsActive = true,
                            Name = "Boligrafo tinta negra x12",
                            Price = 9800.0,
                            PublicId = "PRD-003",
                            Stock = 350
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-4000-8000-000000000004"),
                            CategoryId = new Guid("c0000000-0000-4000-8000-000000000001"),
                            Description = "Set de 4 marcadores borrables en seco para tablero acrilico.",
                            IsActive = true,
                            Name = "Marcador borrable x4",
                            Price = 15400.0,
                            PublicId = "PRD-004",
                            Stock = 90
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-4000-8000-000000000005"),
                            CategoryId = new Guid("c0000000-0000-4000-8000-000000000002"),
                            Description = "Silla de malla transpirable con soporte lumbar ajustable y apoyabrazos 3D.",
                            IsActive = true,
                            Name = "Silla ergonomica con soporte lumbar",
                            Price = 689000.0,
                            PublicId = "PRD-005",
                            Stock = 25
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-4000-8000-000000000006"),
                            CategoryId = new Guid("c0000000-0000-4000-8000-000000000002"),
                            Description = "Escritorio en L de 150 x 120 cm en madera laminada con pasacables.",
                            IsActive = true,
                            Name = "Escritorio en L 150 cm",
                            Price = 899000.0,
                            PublicId = "PRD-006",
                            Stock = 12
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-4000-8000-000000000007"),
                            CategoryId = new Guid("c0000000-0000-4000-8000-000000000002"),
                            Description = "Archivador metalico vertical de 4 gavetas con cerradura central.",
                            IsActive = true,
                            Name = "Archivador metalico 4 gavetas",
                            Price = 745000.0,
                            PublicId = "PRD-007",
                            Stock = 8
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-4000-8000-000000000008"),
                            CategoryId = new Guid("c0000000-0000-4000-8000-000000000002"),
                            Description = "Cajonera movil de 3 gavetas con ruedas y freno, acabado grafito.",
                            IsActive = true,
                            Name = "Cajonera rodante 3 gavetas",
                            Price = 389000.0,
                            PublicId = "PRD-008",
                            Stock = 15
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-4000-8000-000000000009"),
                            CategoryId = new Guid("c0000000-0000-4000-8000-000000000003"),
                            Description = "Monitor IPS de 27 pulgadas, resolucion 2560x1440, 75 Hz, HDMI y DisplayPort.",
                            IsActive = true,
                            Name = "Monitor 27 pulgadas QHD",
                            Price = 1250000.0,
                            PublicId = "PRD-009",
                            Stock = 18
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-4000-8000-000000000010"),
                            CategoryId = new Guid("c0000000-0000-4000-8000-000000000003"),
                            Description = "Teclado mecanico 75%, switches lineales, conexion Bluetooth y USB-C.",
                            IsActive = true,
                            Name = "Teclado mecanico inalambrico",
                            Price = 329000.0,
                            PublicId = "PRD-010",
                            Stock = 40
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-4000-8000-000000000011"),
                            CategoryId = new Guid("c0000000-0000-4000-8000-000000000003"),
                            Description = "Diadema over-ear con cancelacion activa de ruido y 30 horas de bateria.",
                            IsActive = true,
                            Name = "Diadema con cancelacion de ruido",
                            Price = 459000.0,
                            PublicId = "PRD-011",
                            Stock = 30
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-4000-8000-000000000012"),
                            CategoryId = new Guid("c0000000-0000-4000-8000-000000000003"),
                            Description = "Base con 5 ventiladores silenciosos y altura ajustable en 6 posiciones.",
                            IsActive = true,
                            Name = "Base refrigerante para portatil",
                            Price = 89900.0,
                            PublicId = "PRD-012",
                            Stock = 45
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-4000-8000-000000000013"),
                            CategoryId = new Guid("c0000000-0000-4000-8000-000000000004"),
                            Description = "Organizador de escritorio en metal perforado con 5 compartimentos.",
                            IsActive = true,
                            Name = "Organizador de escritorio 5 compartimentos",
                            Price = 54900.0,
                            PublicId = "PRD-013",
                            Stock = 75
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-4000-8000-000000000014"),
                            CategoryId = new Guid("c0000000-0000-4000-8000-000000000004"),
                            Description = "Paquete por 10 cajas de archivo inactivo en carton kraft con tapa fija.",
                            IsActive = true,
                            Name = "Caja de archivo tapa fija x10",
                            Price = 68000.0,
                            PublicId = "PRD-014",
                            Stock = 60
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-4000-8000-000000000015"),
                            CategoryId = new Guid("c0000000-0000-4000-8000-000000000004"),
                            Description = "Paquete por 6 blocks de notas adhesivas de 76 x 76 mm en colores neon.",
                            IsActive = true,
                            Name = "Notas adhesivas x6",
                            Price = 11200.0,
                            PublicId = "PRD-015",
                            Stock = 180
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-4000-8000-000000000016"),
                            CategoryId = new Guid("c0000000-0000-4000-8000-000000000004"),
                            Description = "Perforadora de 2 huecos con capacidad para 30 hojas y guia metrica.",
                            IsActive = true,
                            Name = "Perforadora industrial 30 hojas",
                            Price = 97500.0,
                            PublicId = "PRD-016",
                            Stock = 22
                        });
                });

            modelBuilder.Entity("TheOffice.Persistence.Models.ProductImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("ProductImages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1000000-0000-4000-8000-000000000001"),
                            IsPrimary = true,
                            ProductId = new Guid("b0000000-0000-4000-8000-000000000001"),
                            PublicId = "PRD-001-IMG-1",
                            SortOrder = 0,
                            Url = "https://placehold.co/600x400/E5E0D6/78716C/png?text=Resma%20de%20papel%20carta%2075g"
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-4000-8000-000000000101"),
                            IsPrimary = false,
                            ProductId = new Guid("b0000000-0000-4000-8000-000000000001"),
                            PublicId = "PRD-001-IMG-2",
                            SortOrder = 1,
                            Url = "https://placehold.co/600x400/E5E0D6/78716C/png?text=Resma%20de%20papel%20carta%2075g%20-%20detalle"
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-4000-8000-000000000201"),
                            IsPrimary = false,
                            ProductId = new Guid("b0000000-0000-4000-8000-000000000001"),
                            PublicId = "PRD-001-IMG-3",
                            SortOrder = 2,
                            Url = "https://placehold.co/600x400/E5E0D6/78716C/png?text=Resma%20de%20papel%20carta%2075g%20-%20en%20uso"
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-4000-8000-000000000002"),
                            IsPrimary = true,
                            ProductId = new Guid("b0000000-0000-4000-8000-000000000002"),
                            PublicId = "PRD-002-IMG-1",
                            SortOrder = 0,
                            Url = "https://placehold.co/600x400/E5E0D6/78716C/png?text=Cuaderno%20argollado%20100%20hojas"
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-4000-8000-000000000102"),
                            IsPrimary = false,
                            ProductId = new Guid("b0000000-0000-4000-8000-000000000002"),
                            PublicId = "PRD-002-IMG-2",
                            SortOrder = 1,
                            Url = "https://placehold.co/600x400/E5E0D6/78716C/png?text=Cuaderno%20argollado%20100%20hojas%20-%20detalle"
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-4000-8000-000000000202"),
                            IsPrimary = false,
                            ProductId = new Guid("b0000000-0000-4000-8000-000000000002"),
                            PublicId = "PRD-002-IMG-3",
                            SortOrder = 2,
                            Url = "https://placehold.co/600x400/E5E0D6/78716C/png?text=Cuaderno%20argollado%20100%20hojas%20-%20en%20uso"
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-4000-8000-000000000003"),
                            IsPrimary = true,
                            ProductId = new Guid("b0000000-0000-4000-8000-000000000003"),
                            PublicId = "PRD-003-IMG-1",
                            SortOrder = 0,
                            Url = "https://placehold.co/600x400/E5E0D6/78716C/png?text=Boligrafo%20tinta%20negra%20x12"
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-4000-8000-000000000004"),
                            IsPrimary = true,
                            ProductId = new Guid("b0000000-0000-4000-8000-000000000004"),
                            PublicId = "PRD-004-IMG-1",
                            SortOrder = 0,
                            Url = "https://placehold.co/600x400/E5E0D6/78716C/png?text=Marcador%20borrable%20x4"
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-4000-8000-000000000104"),
                            IsPrimary = false,
                            ProductId = new Guid("b0000000-0000-4000-8000-000000000004"),
                            PublicId = "PRD-004-IMG-2",
                            SortOrder = 1,
                            Url = "https://placehold.co/600x400/E5E0D6/78716C/png?text=Marcador%20borrable%20x4%20-%20detalle"
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-4000-8000-000000000204"),
                            IsPrimary = false,
                            ProductId = new Guid("b0000000-0000-4000-8000-000000000004"),
                            PublicId = "PRD-004-IMG-3",
                            SortOrder = 2,
                            Url = "https://placehold.co/600x400/E5E0D6/78716C/png?text=Marcador%20borrable%20x4%20-%20en%20uso"
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-4000-8000-000000000005"),
                            IsPrimary = true,
                            ProductId = new Guid("b0000000-0000-4000-8000-000000000005"),
                            PublicId = "PRD-005-IMG-1",
                            SortOrder = 0,
                            Url = "https://placehold.co/600x400/E5E0D6/78716C/png?text=Silla%20ergonomica%20con%20soporte%20lumbar"
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-4000-8000-000000000105"),
                            IsPrimary = false,
                            ProductId = new Guid("b0000000-0000-4000-8000-000000000005"),
                            PublicId = "PRD-005-IMG-2",
                            SortOrder = 1,
                            Url = "https://placehold.co/600x400/E5E0D6/78716C/png?text=Silla%20ergonomica%20con%20soporte%20lumbar%20-%20detalle"
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-4000-8000-000000000205"),
                            IsPrimary = false,
                            ProductId = new Guid("b0000000-0000-4000-8000-000000000005"),
                            PublicId = "PRD-005-IMG-3",
                            SortOrder = 2,
                            Url = "https://placehold.co/600x400/E5E0D6/78716C/png?text=Silla%20ergonomica%20con%20soporte%20lumbar%20-%20en%20uso"
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-4000-8000-000000000305"),
                            IsPrimary = false,
                            ProductId = new Guid("b0000000-0000-4000-8000-000000000005"),
                            PublicId = "PRD-005-IMG-4",
                            SortOrder = 3,
                            Url = "https://placehold.co/600x400/E5E0D6/78716C/png?text=Silla%20ergonomica%20con%20soporte%20lumbar%20-%20empaque"
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-4000-8000-000000000006"),
                            IsPrimary = true,
                            ProductId = new Guid("b0000000-0000-4000-8000-000000000006"),
                            PublicId = "PRD-006-IMG-1",
                            SortOrder = 0,
                            Url = "https://placehold.co/600x400/E5E0D6/78716C/png?text=Escritorio%20en%20L%20150%20cm"
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-4000-8000-000000000106"),
                            IsPrimary = false,
                            ProductId = new Guid("b0000000-0000-4000-8000-000000000006"),
                            PublicId = "PRD-006-IMG-2",
                            SortOrder = 1,
                            Url = "https://placehold.co/600x400/E5E0D6/78716C/png?text=Escritorio%20en%20L%20150%20cm%20-%20detalle"
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-4000-8000-000000000206"),
                            IsPrimary = false,
                            ProductId = new Guid("b0000000-0000-4000-8000-000000000006"),
                            PublicId = "PRD-006-IMG-3",
                            SortOrder = 2,
                            Url = "https://placehold.co/600x400/E5E0D6/78716C/png?text=Escritorio%20en%20L%20150%20cm%20-%20en%20uso"
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-4000-8000-000000000007"),
                            IsPrimary = true,
                            ProductId = new Guid("b0000000-0000-4000-8000-000000000007"),
                            PublicId = "PRD-007-IMG-1",
                            SortOrder = 0,
                            Url = "https://placehold.co/600x400/E5E0D6/78716C/png?text=Archivador%20metalico%204%20gavetas"
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-4000-8000-000000000107"),
                            IsPrimary = false,
                            ProductId = new Guid("b0000000-0000-4000-8000-000000000007"),
                            PublicId = "PRD-007-IMG-2",
                            SortOrder = 1,
                            Url = "https://placehold.co/600x400/E5E0D6/78716C/png?text=Archivador%20metalico%204%20gavetas%20-%20detalle"
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-4000-8000-000000000207"),
                            IsPrimary = false,
                            ProductId = new Guid("b0000000-0000-4000-8000-000000000007"),
                            PublicId = "PRD-007-IMG-3",
                            SortOrder = 2,
                            Url = "https://placehold.co/600x400/E5E0D6/78716C/png?text=Archivador%20metalico%204%20gavetas%20-%20en%20uso"
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-4000-8000-000000000008"),
                            IsPrimary = true,
                            ProductId = new Guid("b0000000-0000-4000-8000-000000000008"),
                            PublicId = "PRD-008-IMG-1",
                            SortOrder = 0,
                            Url = "https://placehold.co/600x400/E5E0D6/78716C/png?text=Cajonera%20rodante%203%20gavetas"
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-4000-8000-000000000108"),
                            IsPrimary = false,
                            ProductId = new Guid("b0000000-0000-4000-8000-000000000008"),
                            PublicId = "PRD-008-IMG-2",
                            SortOrder = 1,
                            Url = "https://placehold.co/600x400/E5E0D6/78716C/png?text=Cajonera%20rodante%203%20gavetas%20-%20detalle"
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-4000-8000-000000000208"),
                            IsPrimary = false,
                            ProductId = new Guid("b0000000-0000-4000-8000-000000000008"),
                            PublicId = "PRD-008-IMG-3",
                            SortOrder = 2,
                            Url = "https://placehold.co/600x400/E5E0D6/78716C/png?text=Cajonera%20rodante%203%20gavetas%20-%20en%20uso"
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-4000-8000-000000000009"),
                            IsPrimary = true,
                            ProductId = new Guid("b0000000-0000-4000-8000-000000000009"),
                            PublicId = "PRD-009-IMG-1",
                            SortOrder = 0,
                            Url = "https://placehold.co/600x400/E5E0D6/78716C/png?text=Monitor%2027%20pulgadas%20QHD"
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-4000-8000-000000000109"),
                            IsPrimary = false,
                            ProductId = new Guid("b0000000-0000-4000-8000-000000000009"),
                            PublicId = "PRD-009-IMG-2",
                            SortOrder = 1,
                            Url = "https://placehold.co/600x400/E5E0D6/78716C/png?text=Monitor%2027%20pulgadas%20QHD%20-%20detalle"
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-4000-8000-000000000209"),
                            IsPrimary = false,
                            ProductId = new Guid("b0000000-0000-4000-8000-000000000009"),
                            PublicId = "PRD-009-IMG-3",
                            SortOrder = 2,
                            Url = "https://placehold.co/600x400/E5E0D6/78716C/png?text=Monitor%2027%20pulgadas%20QHD%20-%20en%20uso"
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-4000-8000-000000000309"),
                            IsPrimary = false,
                            ProductId = new Guid("b0000000-0000-4000-8000-000000000009"),
                            PublicId = "PRD-009-IMG-4",
                            SortOrder = 3,
                            Url = "https://placehold.co/600x400/E5E0D6/78716C/png?text=Monitor%2027%20pulgadas%20QHD%20-%20empaque"
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-4000-8000-000000000010"),
                            IsPrimary = true,
                            ProductId = new Guid("b0000000-0000-4000-8000-000000000010"),
                            PublicId = "PRD-010-IMG-1",
                            SortOrder = 0,
                            Url = "https://placehold.co/600x400/E5E0D6/78716C/png?text=Teclado%20mecanico%20inalambrico"
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-4000-8000-000000000110"),
                            IsPrimary = false,
                            ProductId = new Guid("b0000000-0000-4000-8000-000000000010"),
                            PublicId = "PRD-010-IMG-2",
                            SortOrder = 1,
                            Url = "https://placehold.co/600x400/E5E0D6/78716C/png?text=Teclado%20mecanico%20inalambrico%20-%20detalle"
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-4000-8000-000000000210"),
                            IsPrimary = false,
                            ProductId = new Guid("b0000000-0000-4000-8000-000000000010"),
                            PublicId = "PRD-010-IMG-3",
                            SortOrder = 2,
                            Url = "https://placehold.co/600x400/E5E0D6/78716C/png?text=Teclado%20mecanico%20inalambrico%20-%20en%20uso"
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-4000-8000-000000000011"),
                            IsPrimary = true,
                            ProductId = new Guid("b0000000-0000-4000-8000-000000000011"),
                            PublicId = "PRD-011-IMG-1",
                            SortOrder = 0,
                            Url = "https://placehold.co/600x400/E5E0D6/78716C/png?text=Diadema%20con%20cancelacion%20de%20ruido"
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-4000-8000-000000000111"),
                            IsPrimary = false,
                            ProductId = new Guid("b0000000-0000-4000-8000-000000000011"),
                            PublicId = "PRD-011-IMG-2",
                            SortOrder = 1,
                            Url = "https://placehold.co/600x400/E5E0D6/78716C/png?text=Diadema%20con%20cancelacion%20de%20ruido%20-%20detalle"
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-4000-8000-000000000211"),
                            IsPrimary = false,
                            ProductId = new Guid("b0000000-0000-4000-8000-000000000011"),
                            PublicId = "PRD-011-IMG-3",
                            SortOrder = 2,
                            Url = "https://placehold.co/600x400/E5E0D6/78716C/png?text=Diadema%20con%20cancelacion%20de%20ruido%20-%20en%20uso"
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-4000-8000-000000000012"),
                            IsPrimary = true,
                            ProductId = new Guid("b0000000-0000-4000-8000-000000000012"),
                            PublicId = "PRD-012-IMG-1",
                            SortOrder = 0,
                            Url = "https://placehold.co/600x400/E5E0D6/78716C/png?text=Base%20refrigerante%20para%20portatil"
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-4000-8000-000000000112"),
                            IsPrimary = false,
                            ProductId = new Guid("b0000000-0000-4000-8000-000000000012"),
                            PublicId = "PRD-012-IMG-2",
                            SortOrder = 1,
                            Url = "https://placehold.co/600x400/E5E0D6/78716C/png?text=Base%20refrigerante%20para%20portatil%20-%20detalle"
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-4000-8000-000000000212"),
                            IsPrimary = false,
                            ProductId = new Guid("b0000000-0000-4000-8000-000000000012"),
                            PublicId = "PRD-012-IMG-3",
                            SortOrder = 2,
                            Url = "https://placehold.co/600x400/E5E0D6/78716C/png?text=Base%20refrigerante%20para%20portatil%20-%20en%20uso"
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-4000-8000-000000000013"),
                            IsPrimary = true,
                            ProductId = new Guid("b0000000-0000-4000-8000-000000000013"),
                            PublicId = "PRD-013-IMG-1",
                            SortOrder = 0,
                            Url = "https://placehold.co/600x400/E5E0D6/78716C/png?text=Organizador%20de%20escritorio%205%20compartimentos"
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-4000-8000-000000000113"),
                            IsPrimary = false,
                            ProductId = new Guid("b0000000-0000-4000-8000-000000000013"),
                            PublicId = "PRD-013-IMG-2",
                            SortOrder = 1,
                            Url = "https://placehold.co/600x400/E5E0D6/78716C/png?text=Organizador%20de%20escritorio%205%20compartimentos%20-%20detalle"
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-4000-8000-000000000213"),
                            IsPrimary = false,
                            ProductId = new Guid("b0000000-0000-4000-8000-000000000013"),
                            PublicId = "PRD-013-IMG-3",
                            SortOrder = 2,
                            Url = "https://placehold.co/600x400/E5E0D6/78716C/png?text=Organizador%20de%20escritorio%205%20compartimentos%20-%20en%20uso"
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-4000-8000-000000000014"),
                            IsPrimary = true,
                            ProductId = new Guid("b0000000-0000-4000-8000-000000000014"),
                            PublicId = "PRD-014-IMG-1",
                            SortOrder = 0,
                            Url = "https://placehold.co/600x400/E5E0D6/78716C/png?text=Caja%20de%20archivo%20tapa%20fija%20x10"
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-4000-8000-000000000114"),
                            IsPrimary = false,
                            ProductId = new Guid("b0000000-0000-4000-8000-000000000014"),
                            PublicId = "PRD-014-IMG-2",
                            SortOrder = 1,
                            Url = "https://placehold.co/600x400/E5E0D6/78716C/png?text=Caja%20de%20archivo%20tapa%20fija%20x10%20-%20detalle"
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-4000-8000-000000000214"),
                            IsPrimary = false,
                            ProductId = new Guid("b0000000-0000-4000-8000-000000000014"),
                            PublicId = "PRD-014-IMG-3",
                            SortOrder = 2,
                            Url = "https://placehold.co/600x400/E5E0D6/78716C/png?text=Caja%20de%20archivo%20tapa%20fija%20x10%20-%20en%20uso"
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-4000-8000-000000000015"),
                            IsPrimary = true,
                            ProductId = new Guid("b0000000-0000-4000-8000-000000000015"),
                            PublicId = "PRD-015-IMG-1",
                            SortOrder = 0,
                            Url = "https://placehold.co/600x400/E5E0D6/78716C/png?text=Notas%20adhesivas%20x6"
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-4000-8000-000000000016"),
                            IsPrimary = true,
                            ProductId = new Guid("b0000000-0000-4000-8000-000000000016"),
                            PublicId = "PRD-016-IMG-1",
                            SortOrder = 0,
                            Url = "https://placehold.co/600x400/E5E0D6/78716C/png?text=Perforadora%20industrial%2030%20hojas"
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-4000-8000-000000000116"),
                            IsPrimary = false,
                            ProductId = new Guid("b0000000-0000-4000-8000-000000000016"),
                            PublicId = "PRD-016-IMG-2",
                            SortOrder = 1,
                            Url = "https://placehold.co/600x400/E5E0D6/78716C/png?text=Perforadora%20industrial%2030%20hojas%20-%20detalle"
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-4000-8000-000000000216"),
                            IsPrimary = false,
                            ProductId = new Guid("b0000000-0000-4000-8000-000000000016"),
                            PublicId = "PRD-016-IMG-3",
                            SortOrder = 2,
                            Url = "https://placehold.co/600x400/E5E0D6/78716C/png?text=Perforadora%20industrial%2030%20hojas%20-%20en%20uso"
                        });
                });

            modelBuilder.Entity("TheOffice.Persistence.Models.ProductVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("ProductVariants");
                });

            modelBuilder.Entity("TheOffice.Persistence.Models.Product", b =>
                {
                    b.HasOne("TheOffice.Persistence.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("TheOffice.Persistence.Models.ProductImage", b =>
                {
                    b.HasOne("TheOffice.Persistence.Models.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("TheOffice.Persistence.Models.ProductVariant", b =>
                {
                    b.HasOne("TheOffice.Persistence.Models.Product", "Product")
                        .WithMany("Variants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("TheOffice.Persistence.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("TheOffice.Persistence.Models.Product", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Variants");
                });
#pragma warning restore 612, 618
        }
    }
}
